export const ACTIONS = {
    ADD_TO_CART: 'ADD_TO_CART',
    REMOVE_FROM_CART: 'REMOVE_FROM_CART',
    INCREMENT_ITEM: 'INCREMENT_ITEM',
    DECREMENT_ITEM: 'DECREMENT_ITEM',
    CLEAR_CART: 'CLEAR_CART',
    SET_VISIBILITY_FILTER: 'SET_VISIBLITY_FILTER',
    SET_ORDERING_FILTER: 'SET_ORDERING_FILTER',
};

export const VISIBILITY_FILTERS = {
    SHOW_ALL: 'SHOW_ALL',
    PAPER: 'PAPER',
    OFFICE_SUPPLIES: 'OFFICE_SUPPLIES',
    MISC: 'MISC',
};

export const ORDERING_FILTER = {
    BY_PRICE: 'BY_PRICE',
    BY_TYPE: 'BY_TYPE',
    ASCENDING: 'ASCENDING',
    DESCENDING: 'DESCENDING',
};

